name: 'Changelog Notifier'
description: 'Notifies you in Telegram when there is a new release'
inputs:
  prefixes:
    description: 'Prefixes to search for'
    required: false
    default: |-
      feat
      fix
      docs
      style
      refactor
      perf
      test
      chore
  token: 
    description: 'Telegram bot token'
    required: true
  chat_id:
    description: 'Telegram chat id'
    required: true
  project_name:
    description: 'Project name'
    required: false
  commits:
    description: 'Commits'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'